### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Fyxren**
This PR contains the Dutch translation used in The Netherlands and in a part of Belgium.

Translation version: 14 >> 15

### CODE REVIEW

**Comment by Fyxren** [comment]
> I asked a fellow KFP (Koala) for some comments on Dutch:
> 
> ```
> It looks good! The only part that I'd change would be the low and moderate uniqueness. 
> Right now it has low = Gewoon and moderate = Ongewoon, but Gewoon and Ongewoon translate more to Usual and Unusual than Common and Rare. 
> Personally I would change them to low = Vaak voorkomend (translates to Often occurring) and moderate = Zeldzaam (actually translates to Rare)
> ```

Good point actually, I didn't really know what to put there. I have no idea how I didn't came with "Vaak voorkomend" and "Zeldzaam". I will update it, thank you!

**Review by uetchy — APPROVED** [review]

**Comment by uetchy** [comment]
Looks great! Thanks for the great contributions⚡️

**Comment by uetchy** [comment]
@all-contributors add @Fyxren for translation

**Comment by uetchy** [comment]
@all-contributors add @DaniruKun for review

**Pull request merged**
